version: 2.1
imports:
  full-pipeline:
    src: ./full-pipeline.yaml
  library:
    src: ./library.yaml
  #
  # Following is how Git based http(s) imports can be specified. A personal access token is required
  # with Git, there are two options 1) use the special HTTP_AUTHORIZATION_TOKEN secret 2) specifiy the 
  # YAML attribute http-authorization-token and feed in any environment variable
  #
  # (Option 1: HTTP_AUTHORIZATION_TOKEN secret)
  # library: 
  #   src: https://github.com/raw/ci/cix/master/docs/examples/import/library.yaml
  #
  # (Option 2: Use any other secret with YAML)
  # library:
  #   src: https://github.com/raw/ci/cix/master/docs/examples/import/library.yaml
  #   http_authorization_token: $$CIX_GIT_TOKEN # must be passed via -s
pipeline:
  - import:
      - library.phase1:
          environment:
            - name: CHANGELIST
              value: 222123123
            - name: P4PORT
              value: ssl:p4proxy.soma.salesforce.com:1999 # dev P4PORT
            # other environment values will remain the same (that is, P4PORT=$$P4PORT, etc.)
            # and will be substituted as normal
      - library.phase2
  - step:
      name: basic
      image: alpine:3.9
      commands:
        - hostname
  - import:
      - full-pipeline:
          environment:
            - name: FOO
              value: bar # step defined above should output 'bar'
