version: 2.1
pipeline:
  - step:
      name: environment-built-ins
      image: alpine:3.9
      commands:
        # these are included in each pipeline by default, no need to add them to the environments section.
        # https://opensource.salesforce.com/cix/#/reference/environment
        - echo $CIX_HOSTNAME
        - echo $CIX_STEP_NAME
        - echo $CIX_NETWORK_NAME
        - echo $CIX_CONTAINER_NAME
        - echo $CIX_EXECUTION_ID
        - echo $CIX_SERVER_PORT
        - pwd
        - echo $CIX_WORKDIR
        - echo $CIX_WORKSPACE
        - echo $CIX_TEMP
  - step:
      name: override-work-dir
      image: alpine:3.9
      working-dir: /bin
      workspace-mount-point: /tmp
      commands:
        - pwd
        - echo $CIX_WORKDIR
        - echo $CIX_WORKSPACE
