version: 2.1
pipeline:
  - step:
      name: environment
      image: alpine:3.9
      environment:
        - name: FOO
          # value passed in via '-e FOO=foo'
          value: $$FOO
        - name: BAR
          # value passed in via '-e BAR=bar'
          value: $$BAR
          # default passed in via '-e BAR_DEFAULT=bar-default'
          default: $$BAR_DEFAULT
        - name: BAZ
          # when value is omitted, value == $$BAZ,
          # passed in via '-e BAZ=baz'
          default: baz-default
      commands:
        - echo $FOO
        - echo $BAR
        - echo $BAZ
