version: 2.1
pipeline:
  - step:
      name: for-each-empty
      image: alpine:3.9   
      for-each: $$FOO
      element-variable: ELEMENT
      parallel: true
      commands-output: minimal
      commands:
        - echo $ELEMENT
