version: 2.1
pipeline:
  - steps:
      name: 1
      pipeline:
        - step:
            name: 1.1
            image: alpine:3.9
            commands:
              - echo '1.1 completed (serial)'
        - steps:
            name: 1.2
            parallel: true
            pipeline:
              - step:
                  name: 1.2.1
                  image: alpine:3.9
                  commands:
                    - echo '1.2.1 starting (parallel)'
                    - sleep 3
                    - echo '1.2.1 completed (parallel)'
              - step:
                  name: 1.2.2
                  image: alpine:3.9
                  commands:
                    - echo '1.2.2 completed (parallel)'
        - steps:
            name: 1.3
            pipeline:
              - step:
                  name: 1.3.1
                  image: alpine:3.9
                  commands:
                    - echo '1.3.1 completed (serial)'
              - step:
                  name: 1.3.2
                  image: alpine:3.9
                  commands:
                    - echo '1.3.2 completed (serial)'
  - step:
      name: 2.1
      image: alpine:3.9
      commands:
        - echo '2.1 completed (serial)'
