version: 2.1
pipeline:
  - step:
      name: secrets
      image: alpine:3.9
      environment:
        - name: FOO
          value: $$SECRET_FOO
        - name: BAR
          value: $$SECRET_BAR
      commands:
        - echo $FOO
        - echo $BAR
        - echo Multiple secrets such as $FOO, $FOO, and $BAR on the same line will be masked
