version: 2.1
pipeline:
  - step:
      name: secrets
      image: alpine:3.9
      environment:
        - name: FOO
          value: $$SECRET_FOO_FROM_COMMAND
        - name: BAR
          value: $$SECRET_BAR_FROM_COMMAND
      commands:
        - echo $FOO
        - echo $BAR
        - echo Multiple secrets such as $FOO, $FOO, and $BAR on the same line should be masked
