version: 2.1
pipeline:
  - step:
      name: secrets
      image: alpine:3.9
      environment:
        - name: FOO
          value: $$FOO_FROM_PROMPT
          default: 'foo_is_unset'
        - name: BAR
          value: $$BAR_FROM_STDIN
          default: 'bar_is_unset'
        - name: BAZ
          value: $$BAZ_FROM_JSON_STDIN
          default: 'baz_is_unset'
        - name: QUX
          value: $$QUX_FROM_JSON_STDIN
          default: 'qux_is_unset'
      commands:
        - ': "Expecting the following secret vars:"'
        - ': "  - FOO_FROM_PROMPT"'
        - ': "  - BAR_FROM_STDIN"'
        - ': "  - BAZ_FROM_JSON_STDIN"'
        - ': "  - QUX_FROM_JSON_STDIN"'
        - echo "When secrets are printed out such as $FOO, $BAR, $BAZ, and $QUX, they will be masked."
        - ': "Shhh... these are really:"'
        - for s in "$FOO" "$BAR" "$BAZ" "$QUX"; do echo "  $s" | sed 's/\b/ /g'; done
